name: Build Vue3 and Deploy to Github Page

on:
    push:
        branches:
            - dev

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Check Out Repository
              uses: actions/checkout@v4
        
            - name: Install Dependencies
              run: npm install
        
            - name: Build Project
              run: npm run build
        
            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./dist 
                publish_branch: master